#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("pikappDes.Droid.Resource", IsApplication=true)]

namespace pikappDes.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int splash_background = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020008
			public const int background = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int background2 = 2130837513;
			
			// aapt resource value: 0x7F02000C
			public const int backgroundblur_notes2 = 2130837516;
			
			// aapt resource value: 0x7F02000A
			public const int background_notes = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int background_notes2 = 2130837515;
			
			// aapt resource value: 0x7F02000D
			public const int detail_background = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int eaxi = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int logo1 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int masterbackground = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int masterbackground2 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int msg = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int msg_notif = 2130837523;
			
			// aapt resource value: 0x7F020000
			public const int OffToggle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int OnToggle = 2130837505;
			
			// aapt resource value: 0x7F020014
			public const int pin = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int pinC = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int pinS = 2130837526;
			
			// aapt resource value: 0x7F020002
			public const int RAW_disconnect = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int RAW_history = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int RAW_map = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int RAW_msg = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int RAW_options = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int RAW_proAcc = 2130837511;
			
			// aapt resource value: 0x7F020017
			public const int splash_screen = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int InfoWindowSubtitle = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int InfoWindowTitle = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int sliding_tabs = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int toolbar = 2130903043;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int CustomInfoWindow = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Tabbar = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Toolbar = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int MyTheme_Splash = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
